### ISSUE TITLE
Ubuntu 20 does not have jq preinstalled, can you add it?

### ISSUE THREAD

**Issue by mihailstoynov** [plasticrake/ansible-role-duplicacy_install#1]
- package: name=jq

**Comment by plasticrake** [comment]
It should already be doing that:

https://github.com/plasticrake/ansible-role-duplicacy_install/blob/5a0bb7af8afd026af290d96194f928d13e5002c8/tasks/main.yml#L39-L46

**Comment by mihailstoynov** [comment]
you can close it then, if I have more info, I'll reopen it
